baseline:
  compare_to_random: true
  random_episodes: 50
curriculum:
  enabled: true
  phases:
  - episodes: 500
    target: 200
  - episodes: 500
    target: 300
learning:
  batch_size: 64
  epsilon_decay: 0.995
  epsilon_end: 0.05
  epsilon_start: 1.0
  gamma: 0.99
  lr: 0.001
  tau: 0.005
logging:
  log_frequency: 50
  verbose: true
model:
  save_dir: models
network:
  hidden_dim: 128
replay:
  alpha: 0.6
  beta_end: 1.0
  beta_start: 0.4
  capacity: 50000
training:
  checkpoint_frequency: 500
  eval_episodes: 50
  eval_frequency: 250
  max_steps_per_episode: 100
  num_episodes: 1000
